server:
  port: 8081
  application:
    name: Spring 3 and Keycloak

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.example: DEBUG
  pattern:
     console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %5p [%logger{1}] %m%n"
